-- Problem: Select By ID
-- Track: SQL Basic
-- Difficulty: Easy
-- Max score: 10
-- Concepts: SELECT, WHERE, ID filtering
-- Status: Not started
-- Source: HackerRank SQL practice
--
-- Task summary:
-- Return the row that matches the requested ID value.
--
-- Query:
-- Pending accepted solution.
--
-- Explanation:
-- Pending explanation after acceptance.
