-- Problem: Japanese Cities' Names
-- Track: SQL Basic
-- Difficulty: Easy
-- Max score: 10
-- Concepts: SELECT specific column, WHERE, country code filtering
-- Status: Not started
-- Source: HackerRank SQL practice
--
-- Task summary:
-- Return only city names for records from the requested country.
--
-- Query:
-- Pending accepted solution.
--
-- Explanation:
-- Pending explanation after acceptance.
