-- Problem: Weather Observation Station 1
-- Track: SQL Basic
-- Difficulty: Easy
-- Max score: 15
-- Concepts: SELECT, column projection
-- Status: Not started
-- Source: HackerRank SQL practice
--
-- Task summary:
-- Pending original task summary.
--
-- Query:
-- Pending accepted solution.
--
-- Explanation:
-- Pending explanation after acceptance.
