-- Problem: Weather Observation Station 6
-- Track: SQL Basic
-- Difficulty: Easy
-- Max score: 10
-- Concepts: DISTINCT, string pattern filtering
-- Status: Not started
-- Source: HackerRank SQL practice
--
-- Task summary:
-- Pending original task summary.
--
-- Query:
-- Pending accepted solution.
--
-- Explanation:
-- Pending explanation after acceptance.
