-- Problem: Revising Aggregations - The Count Function
-- Track: SQL Basic
-- Difficulty: Easy
-- Max score: 10
-- Concepts: COUNT, WHERE
-- Status: Not started
-- Source: HackerRank SQL practice
--
-- Task summary:
-- Pending original task summary.
--
-- Query:
-- Pending accepted solution.
--
-- Explanation:
-- Pending explanation after acceptance.
