-- Problem: Average Population
-- Track: SQL Basic
-- Difficulty: Easy
-- Max score: 10
-- Concepts: AVG, rounding or flooring
-- Status: Not started
-- Source: HackerRank SQL practice
--
-- Task summary:
-- Pending original task summary.
--
-- Query:
-- Pending accepted solution.
--
-- Explanation:
-- Pending explanation after acceptance.
