-- Problem: Weather Observation Station 13
-- Track: SQL Basic
-- Difficulty: Easy
-- Max score: 10
-- Concepts: SUM, range filtering, numeric rounding
-- Status: Not started
-- Source: HackerRank SQL practice
--
-- Task summary:
-- Pending original task summary.
--
-- Query:
-- Pending accepted solution.
--
-- Explanation:
-- Pending explanation after acceptance.
