-- Problem: Weather Observation Station 17
-- Track: SQL Basic
-- Difficulty: Easy
-- Max score: 15
-- Concepts: subquery, filtering by aggregate, numeric formatting
-- Status: Not started
-- Source: HackerRank SQL practice
--
-- Task summary:
-- Pending original task summary.
--
-- Query:
-- Pending accepted solution.
--
-- Explanation:
-- Pending explanation after acceptance.
