-- Problem: Weather Observation Station 19
-- Track: SQL Basic
-- Difficulty: Medium
-- Max score: 30
-- Concepts: aggregate coordinates, distance formula, numeric formatting
-- Status: Not started
-- Source: HackerRank SQL practice
--
-- Task summary:
-- Pending original task summary.
--
-- Query:
-- Pending accepted solution.
--
-- Explanation:
-- Pending explanation after acceptance.
