-- Problem: Average Population of Each Continent
-- Track: SQL Basic
-- Difficulty: Easy
-- Max score: 10
-- Concepts: INNER JOIN, GROUP BY, AVG, numeric formatting
-- Status: Not started
-- Source: HackerRank SQL practice
--
-- Task summary:
-- Pending original task summary.
--
-- Query:
-- Pending accepted solution.
--
-- Explanation:
-- Pending explanation after acceptance.
